<?php
/**
 * Created by PhpStorm.
 * User: yunzhong
 * Date: 2018/3/28
 * Time: 15:43
 */

namespace Yunshop\GroupPurchase\models;


class Goods extends \app\frontend\models\Goods
{

    public function scopePluginId($query, $pluginId = 0)
    {
        return parent::scopePluginId($query, 31); // TODO: Change the autogenerated stub
    }

    public $appends = [];

    public function PurchasePrice()
    {
        return request()->input('price');
    }

    public function getPriceAttribute()
    {
        return $this->PurchasePrice();

    }
    public function getCostPriceAttribute()
    {
        return $this->PurchasePrice();
    }
    public function getMarketPriceAttribute()
    {
        return $this->PurchasePrice();
    }
}