<?php

namespace Yunshop\LeaseToy\models\orderGoods;

use app\common\models\BaseModel;
use Illuminate\Database\Eloquent\SoftDeletes;
use app\frontend\models\Order;

/**
* Author: 芸众商城 www.yunzshop.com
* Date: 2018/3/13
* Time: 11:54
*/
class LeaseToyOrderGoodsModel extends BaseModel
{
    
    use SoftDeletes;

    protected $table = 'yz_lease_toy_order_goods';
    public $orderGoods;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }

    public function setOrderGoods(PreOrderGoods $orderGoods)
    {
        $this->orderGoods = $orderGoods;
        $orderGoods->orderLeaseGoods->push($this);

    }
    public function save(array $options = [])
    {
        $this->lease_member_id = $this->orderGoods->uid;
        $this->uniacid = $this->orderGoods->uniacid;
        $this->order_sn = Order::find($this->orderGoods->order_id)->order_sn;
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}