<?php
/**
 * Created by PhpStorm.
 * User: king
 * Date: 2018/9/17
 * Time: 上午10:40
 */

namespace Yunshop\Designer\Common\Config;


class Menu
{
    public static function menu()
    {
        return [
            'name'             => '装修',
            'type'             => 'tool',
            'url'              => 'plugin.designer.Backend.Modules.Page.Controllers.records',
            'url_params'       => '',
            'permit'           => 1,
            'menu'             => 1,
            'icon'             => 'fa-gavel',
            'list_icon'        => 'designer',
            'top_show'         => 0,
            'left_first_show'  => 1,
            'left_second_show' => 1,
            'parents'          => [],
            'child'            => [
                //应用到商城的一些白名单
                'designer_apply_route' => [
                    'name'       => '搜索商品',
                    'permit'     => 0,
                    'menu'       => 0,
                    'icon'       => '',
                    'url'        => 'goods.goods.getMyLinkGoods',
                    'url_params' => '',
                    'item'       => 'designer_apply_route',
                    'parents'    => ['designer'],
                    'child'      => [
                        'designer_apply_route1'    => [
                            'name'       => '搜索商品',
                            'url'        => 'plugin.designer.admin.list.searchGoods',
                            'url_params' => '',
                            'permit'     => 0,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_apply_route1',
                            'parents'    => ['designer', 'designer_list'],
                        ],
                        'designerSearchForm'       => [
                            'name'       => '搜索表单',
                            'url'        => 'plugin.designer.admin.list.searchForm',
                            'url_params' => '',
                            'permit'     => 0,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designerSearchForm',
                            'parents'    => ['designer', 'designer_list'],
                        ],
                        'designer_apply_route2'    => [
                            'name'       => '搜索商品',
                            'url'        => 'plugin.designer.admin.list.selectCategoryGoods',
                            'url_params' => '',
                            'permit'     => 0,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_apply_route2',
                            'parents'    => ['designer', 'designer_list'],
                        ],
                        'designer_apply_route3'    => [
                            'name'       => '搜索商品',
                            'url'        => 'plugin.designer.admin.list.selectSearchGoods',
                            'url_params' => '',
                            'permit'     => 0,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_apply_route3',
                            'parents'    => ['designer', 'designer_list'],
                        ],
                        'designer_apply_route4'    => [
                            'name'       => '搜索限时购商品',
                            'url'        => 'plugin.designer.admin.list.searchFlashsale',
                            'url_params' => '',
                            'permit'     => 0,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_apply_route4',
                            'parents'    => ['designer', 'designer_list'],
                        ],
                        'designer_search_article'  => [
                            'name'       => '搜索限时购商品',
                            'url'        => 'plugin.designer.Backend.Modules.Page.Controllers.search-article.index',
                            'url_params' => '',
                            'permit'     => 0,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_search_article',
                            'parents'    => ['designer', 'designer_apply_route'],
                        ],
                        'designer_search_assemble' => [
                            'name'       => '搜索拼团商品',
                            'url'        => 'plugin.designer.Backend.Modules.Page.Controllers.search-fight-groups.index',
                            'url_params' => '',
                            'permit'     => 0,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_search_assemble',
                            'parents'    => ['designer', 'designer_list'],
                        ],
                    ],
                ],

                'designer_template'       => [
                    'name'       => '模板管理',
                    'permit'     => 1,
                    'menu'       => 1,
                    'icon'       => 'fa-magic',
                    'url'        => 'plugin.designer.admin.template.index',
                    'url_params' => '',
                    'item'       => 'designer_template',
                    'parents'    => ['designer'],
                    'child'      => [
                        'designer_template_set' => [
                            'name'       => '切换模板',
                            'url'        => 'plugin.designer.admin.Template.setTmp',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'item'       => 'designer_template_set',
                            'parents'    => ['designer', 'designer_template'],
                        ],
                    ]
                ],
                'designer_records'        => [
                    'name'       => '店铺装修',
                    'permit'     => 1,
                    'menu'       => 1,
                    'icon'       => 'fa-magic',
                    'url'        => 'plugin.designer.Backend.Modules.Page.Controllers.records',
                    'url_params' => '',
                    'item'       => 'designer_records',
                    'parents'    => ['designer'],
                    'child'      => [

                        'designer_records_index'         => [
                            'name'       => '浏览记录',
                            'url'        => 'plugin.designer.Backend.Modules.Page.Controllers.records.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'item'       => 'designer_records_index',
                            'parents'    => ['designer', 'designer_records'],
                        ],
                        'designer_records_search_coupon' => [
                            'name'       => '查询优惠卷',
                            'url'        => 'plugin.designer.admin.list.searchCoupon',
                            'url_params' => '',
                            'permit'     => 0,
                            'menu'       => 0,
                            'icon'       => '',
                            'item'       => 'designer_records_index',
                            'parents'    => ['designer', 'designer_records'],
                        ],
                        'designer_list_preview'     => [
                            'name'       => '预览页面',
                            'url'        => 'plugin.designer.admin.list.preview',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_list_preview',
                            'parents'    => ['designer', 'designer_records'],
                        ],
                        'designer_list_store'       => [
                            'name'       => '添加页面',
                            'url'        => 'plugin.designer.admin.list.store',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_list_store',
                            'parents'    => ['designer', 'designer_records'],
                        ],
                        'designer_list_update'      => [
                            'name'       => '修改页面',
                            'url'        => 'plugin.designer.admin.list.update',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_list_update',
                            'parents'    => ['designer', 'designer_records'],
                        ],
                        'designer_list_destroy'     => [
                            'name'       => '删除页面',
                            'url'        => 'plugin.designer.admin.list.destory',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_list_destroy',
                            'parents'    => ['designer', 'designer_records'],
                        ],
                        'designer_list_set_default' => [
                            'name'       => '修改默认',
                            'url'        => 'plugin.designer.admin.list.setToDefault',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_list_set_default',
                            'parents'    => ['designer', 'designer_records'],
                        ],
                        'designerCopyPage' => [
                            'name'       => '复制页面',
                            'url'        => 'plugin.designer.Backend.Modules.Page.Controllers.copy.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designerCopyPage',
                            'parents'    => ['designer', 'designer_records'],
                        ],
                    ],
                ],
                'designer_member_records' => [
                    'name'       => '会员中心装修',
                    'permit'     => 1,
                    'menu'       => 1,
                    'icon'       => 'fa-magic',
                    'url'        => 'plugin.designer.Backend.Modules.MemberPage.Controllers.records',
                    'url_params' => '',
                    'item'       => 'designer_member_records',
                    'parents'    => ['designer'],
                    'child'      => [
                        'designer_member_records_index'    => [
                            'name'       => '浏览记录',
                            'url'        => 'plugin.designer.Backend.Modules.MemberPage.Controllers.records.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'item'       => 'designer_member_records_index',
                            'parents'    => ['designer', 'designer_member_records'],
                        ],
                        'designer_member_records_store'    => [
                            'name'       => '添加页面',
                            'url'        => 'plugin.designer.Backend.Modules.MemberPage.Controllers.store.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'item'       => 'designer_member_records_store',
                            'parents'    => ['designer', 'designer_member_records'],
                        ],
                        'designer_member_list_preview'     => [
                            'name'       => '预览页面',
                            'url'        => 'plugin.designer.admin.member-list.preview',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_member_list_preview',
                            'parents'    => ['designer', 'designer_member_records'],
                        ],
                        'designer_member_list_store'       => [
                            'name'       => '添加页面',
                            'url'        => 'plugin.designer.admin.member-list.store',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_member_list_store',
                            'parents'    => ['designer', 'designer_member_records'],
                        ],
                        'designer_member_list_update'      => [
                            'name'       => '修改页面',
                            'url'        => 'plugin.designer.admin.member-list.update',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_member_list_update',
                            'parents'    => ['designer', 'designer_member_records'],
                        ],
                        'designer_member_list_destroy'     => [
                            'name'       => '删除页面',
                            'url'        => 'plugin.designer.admin.member-list.destory',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_member_list_destroy',
                            'parents'    => ['designer', 'designer_member_records'],
                        ],
                        'designer_member_list_set_default' => [
                            'name'       => '修改默认',
                            'url'        => 'plugin.designer.admin.member-list.setToDefault',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_member_list_set_default',
                            'parents'    => ['designer', 'designer_member_records'],
                        ],
                    ],
                ],

                'designer_top_menu' => [
                    'name'       => '顶部菜单',
                    'permit'     => 1,
                    'menu'       => 1,
                    'icon'       => 'fa-magic',
                    'url'        => 'plugin.designer.Backend.Modules.TopMenu.Controllers.records',
                    'url_params' => '',
                    'item'       => 'designer_top_menu',
                    'parents'    => ['designer'],
                    'child'      => [
                        'designer_top_menu_records' => [
                            'name'       => '浏览记录',
                            'url'        => 'plugin.designer.Backend.Modules.TopMenu.Controllers.records.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_top_menu_records',
                            'parents'    => ['designer', 'designer_top_menu'],
                        ],
                        'designer_top_menu_add'     => [
                            'name'       => '添加菜单',
                            'url'        => 'plugin.designer.Backend.Modules.TopMenu.Controllers.store.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_top_menu_add',
                            'parents'    => ['designer', 'designer_top_menu'],
                        ],
                    ]
                ],

                'designerBottomMenu' => [
                    'name'       => '底部导航',
                    'permit'     => 1,
                    'menu'       => 1,
                    'icon'       => 'fa-magic',
                    'url'        => 'plugin.designer.Backend.Modules.BottomMenu.Controllers.records',
                    'url_params' => '',
                    'item'       => 'designerBottomMenu',
                    'parents'    => ['designer'],
                    'child'      => [
                        'designerBottomMenuRecords'    => [
                            'name'       => '浏览记录',
                            'url'        => 'plugin.designer.Backend.Modules.BottomMenu.Controllers.records.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designerBottomMenuRecords',
                            'parents'    => ['designer', 'designerBottomMenu'],
                        ],
                        'designerBottomMenuStoreIndex' => [
                            'name'       => '查看编辑',
                            'url'        => 'plugin.designer.Backend.Modules.BottomMenu.Controllers.store.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designerBottomMenuStore',
                            'parents'    => ['designer', 'designerBottomMenu'],
                        ],
                        'designerBottomMenuStore'      => [
                            'name'       => '保存导航',
                            'url'        => 'plugin.designer.Backend.Modules.BottomMenu.Controllers.store.update',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designerBottomMenuStore',
                            'parents'    => ['designer', 'designerBottomMenu'],
                        ],
                        'designerBottomMenuDestroy'    => [
                            'name'       => '删除导航',
                            'url'        => 'plugin.designer.Backend.Modules.BottomMenu.Controllers.destroy.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designerBottomMenuDestroy',
                            'parents'    => ['designer', 'designerBottomMenu'],
                        ],
                        'designerBottomMenuDefault'    => [
                            'name'       => '修改默认',
                            'url'        => 'plugin.designer.Backend.Modules.BottomMenu.Controllers.default.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designerBottomMenuDefault',
                            'parents'    => ['designer', 'designerBottomMenu'],
                        ],
                    ],
                ],

                'designerWeChatAppletBottomMenu' => [
                    'name'       => '小程序导航',
                    'permit'     => 1,
                    'menu'       => 1,
                    'icon'       => 'fa-magic',
                    'url'        => 'plugin.designer.Backend.Modules.WeChatAppletBottomMenu.Controllers.records',
                    'url_params' => '',
                    'item'       => 'designerWeChatAppletBottomMenu',
                    'parents'    => ['designer'],
                    'child'      => [

                        'designerWeChatAppletBottomMenuRecords'    => [
                            'name'       => '浏览记录',
                            'url'        => 'plugin.designer.Backend.Modules.WeChatAppletBottomMenu.Controllers.records.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designerWeChatAppletBottomMenuRecords',
                            'parents'    => ['designer', 'designerWeChatAppletBottomMenu'],
                        ],
                        'designerWeChatAppletBottomMenuStoreIndex' => [
                            'name'       => '查看编辑',
                            'url'        => 'plugin.designer.Backend.Modules.WeChatAppletBottomMenu.Controllers.store.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designerWeChatAppletBottomMenuStoreIndex',
                            'parents'    => ['designer', 'designerWeChatAppletBottomMenu'],
                        ],
                        'designerWeChatAppletBottomMenuStore'      => [
                            'name'       => '保存导航',
                            'url'        => 'plugin.designer.Backend.Modules.WeChatAppletBottomMenu.Controllers.store.update',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designerWeChatAppletBottomMenuStore',
                            'parents'    => ['designer', 'designerWeChatAppletBottomMenu'],
                        ],
                        'designerWeChatAppletBottomMenuDestroy'    => [
                            'name'       => '删除导航',
                            'url'        => 'plugin.designer.Backend.Modules.WeChatAppletBottomMenu.Controllers.destroy.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designerWeChatAppletBottomMenuDestroy',
                            'parents'    => ['designer', 'designerWeChatAppletBottomMenu'],
                        ],
                        'designerWeChatAppletBottomMenuDefault'    => [
                            'name'       => '修改默认',
                            'url'        => 'plugin.designer.Backend.Modules.WeChatAppletBottomMenu.Controllers.default.index',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designerWeChatAppletBottomMenuDefault',
                            'parents'    => ['designer', 'designerWeChatAppletBottomMenu'],
                        ],
                    ]
                ],
                'designer_menus'                 => [
                    'name'       => 'diy模板市场',
                    'permit'     => 1,
                    'menu'       => 1,
                    'icon'       => 'fa-magic',
                    'url'        => 'plugin.designer.admin.diy-market.index',
                    'url_params' => '',
                    'item'       => 'designer_menu',
                    'parents'    => ['designer'],
                    'child'      => [
                        'designer_menu_synchronization'       => [
                            'name'       => '同步数据',
                            'url'        => 'plugin.designer.admin.diy-market.chick-sync',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_menu_synchronization',
                            'parents'    => ['designer', 'designer_menu'],
                            ],
                        'designer_menu_search'       => [
                                'name'       => 'diy模板市场搜索',
                                'url'        => 'plugin.designer.admin.diy-market.search',
                                'url_params' => '',
                                'permit'     => 1,
                                'menu'       => 0,
                                'icon'       => '',
                                'sort'       => 1,
                                'item'       => 'designer_menu_search',
                                'parents'    => ['designer', 'designer_menu'],
                        ],
                        'designer_menu_store'       => [
                            'name'       => '添加修改菜单',
                            'url'        => 'plugin.designer.admin.menu.store',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_menu_store',
                            'parents'    => ['designer', 'designer_menu'],
                        ],
                        'designer_menu_destroy'     => [
                            'name'       => '删除菜单',
                            'url'        => 'plugin.designer.admin.menu.destory',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_menu_destroy',
                            'parents'    => ['designer', 'designer_menu'],
                        ],
                        'designer_menu_set_default' => [
                            'name'       => '修改默认',
                            'url'        => 'plugin.designer.admin.menu.setDefault',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_menu_set_default',
                            'parents'    => ['designer', 'designer_menu'],
                        ],
                        'designer_menu_select'      => [
                            'name'       => '选取模板',
                            'url'        => 'plugin.designer.admin.diy-market.choose',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_menu_select',
                            'parents'    => ['designer', 'designer_menu'],
                        ],
                        'designer_menu_diy_market_search'      => [
                            'name'       => '选择模板分类',
                            'url'        => 'plugin.designer.admin.diy-market.search',
                            'url_params' => '',
                            'permit'     => 1,
                            'menu'       => 0,
                            'icon'       => '',
                            'sort'       => 1,
                            'item'       => 'designer_menu_diy_market_search',
                            'parents'    => ['designer', 'designer_menu'],
                        ],
                    ],
                ],

                'first_screen' => [
                    'name'       => '首屏广告',
                    'permit'     => 1,
                    'menu'       => 1,
                    'icon'       => 'fa-magic',
                    'url'        => 'plugin.designer.admin.first_screen.index',
                    'url_params' => '',
                    'item'       => 'designer_template',
                    'parents'    => ['designer']
                ],

            ]
        ];
    }
}
