<?php
/**
 * Author: 芸众商城 www.yunzshop.com
 * Date: 2018/3/2
 * Time: 下午4:07
 */

namespace Yunshop\LeaseToy\api;


use Yunshop\LeaseToy\models\MemberCart;

class MemberCartController extends \app\frontend\modules\member\controllers\MemberCartController
{
    public function store()
    {
        app('OrderManager')->bind('MemberCart', function ($orderManager, $attributes) {
            return new MemberCart($attributes);
        });

        return parent::store(); // TODO: Change the autogenerated stub
    }

    public function index()
    {

        app('OrderManager')->bind('MemberCart', function ($orderManager, $attributes) {
            return (new MemberCart($attributes))->with('hasOneLeaseGoods');
        });
        return parent::index(); // TODO: Change the autogenerated stub


    }

    public function updateNum()
    {
        $cartId = request()->input('id');
        $num = request()->input('num');
        if ($cartId && $num) {
            $cartModel = MemberCart::find($cartId);
            if ($cartModel) {
                $cartModel->total = $cartModel->total + $num;
                $cartModel->validate();
                if ($cartModel->update()) {
                    $cartModel = MemberCart::find($cartId);
                    return $this->successJson('修改数量成功', $cartModel);
                }
            }
        }
        return $this->errorJson('未获取到数据，请重试！');

        // app('OrderManager')->bind('MemberCart', function ($orderManager, $attributes) {
        //     return new MemberCart($attributes);
        // });
        //return parent::updateNum(); // TODO: Change the autogenerated stub
    }

    public function destroy()
    {
        app('OrderManager')->bind('MemberCart', function ($orderManager, $attributes) {
            return new MemberCart($attributes);
        });
        return parent::destroy(); // TODO: Change the autogenerated stub
    }
}