<?php
/**
 * Created by PhpStorm.
 * User: yunzhong
 * Date: 2018/12/19
 * Time: 9:47
 */

namespace Yunshop\Mryt\models;


use app\common\models\member\ChildrenOfMember;
use Yunshop\SalesCommission\models\SalesCommission;

class MemberChildrenModel extends ChildrenOfMember
{
    public function hasOneMrytMember()
    {
        return parent::hasOne(MrytMemberModel::class,'uid','child_id'); // TODO: Change the autogenerated stub
    }

    public function hasOneSalesCommission()
    {
        return $this->hasOne(SalesCommission::class,'member_id', 'child_id');
    }
}