<?php
/**
 * Created by PhpStorm.
 * User: shenyang
 * Date: 2017/7/27
 * Time: 下午2:23
 */

namespace  Yunshop\LeaseToy\models\order;

class GoodsOption extends \app\frontend\models\GoodsOption
{
    public function scopePluginId($query, $pluginId = 0)
    {
        return parent::scopePluginId($query, 40); // TODO: Change the autogenerated stub
    }

}