<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/23
 * Time: 10:23
 */
namespace Yunshop\HelpUserBuying\shop\controller;

use Yunshop\HelpUserBuying\models\Goods;

class CreateController extends \app\frontend\modules\order\controllers\CreateController
{
    protected $publicAction = ['index'];
    protected $ignoreAction = ['index', 'validateParam', 'getMemberCarts', 'getShopOrder', 'getPluginOrders'];


    public function preAction()
    {
        parent::preAction(); // TODO: Change the autogenerated stub

        app('GoodsManager')->bind('Goods', function ($goodsManager, $attributes) {
            return new Goods($attributes);
        });
    }
}