<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/30
 * Time: 13:51
 */

namespace Yunshop\HelpUserBuying\shop\controller;

use app\frontend\modules\member\services\MemberCartService;
use app\frontend\modules\memberCart\MemberCartCollection;
use Yunshop\HelpUserBuying\models\Goods;

class GoodsBuyController extends \app\frontend\modules\order\controllers\GoodsBuyController
{
    protected $publicAction = ['index'];
    protected $ignoreAction = ['index', 'validateParam', 'getMemberCarts', 'getShopOrder', 'getPluginOrders'];

    public function __construct()
    {

        parent::__construct();
    }

    public function preAction()
    {
        parent::preAction(); // TODO: Change the autogenerated stub

        app('GoodsManager')->bind('Goods', function ($goodsManager, $attributes) {
            return new Goods($attributes);
        });
    }

    protected function getMemberCarts()
    {
        $goods_params = json_decode(request()->input('goods'),true);


        $result = collect($goods_params)->map(function ($memberCart) {
            return MemberCartService::newMemberCart($memberCart);
        });
        $memberCarts = new MemberCartCollection($result);
        $memberCarts->loadRelations();
        return $memberCarts;
    }

    protected function validateParam(){

    }
}