<?php
/**
 * Created by PhpStorm.
 * Date: 2017/3/17
 * Time: 下午12:04
 */

namespace Yunshop\Mryt\admin\model;
use Illuminate\Support\Facades\DB;
use Yunshop\Mryt\store\models\Store;

class MemberShopInfo extends \app\common\models\MemberShopInfo
{
    // 查出该公众号下所有成为推广员的会员，并且这些会员不在yz_mryt_member表里的会员
    public static function getAgentMembers()
    {
        return self::select(['yz_member.uniacid','yz_member.member_id','mc_members.realname','mc_members.mobile','yz_member.agent_time'])
            ->Join('mc_members', function ($join) {$join->on('yz_member.member_id', '=', 'mc_members.uid')
                ->on('yz_member.uniacid', '=', 'mc_members.uniacid');})
            ->leftJoin('yz_mryt_member', function ($join) {$join->on('yz_member.member_id', '=', 'yz_mryt_member.uid')
                ->on('yz_member.uniacid', '=', 'yz_mryt_member.uniacid');})
            ->where('yz_member.status','=',2)
            ->where('yz_member.is_agent','=',1)
            ->where('yz_member.uniacid','=',\YunShop::app()->uniacid)
            ->whereNull('yz_mryt_member.uid')
            ->get();
    }

    public function hasOneStore()
    {
        return parent::hasOne(Store::class, 'uid', 'member_id'); // TODO: Change the autogenerated stub
    }

}